### ISSUE TITLE
Autoconversion from int->double

### ISSUE THREAD

**Issue by skoch9** [geometryprocessing/libigl-python-bindings#17]
Running
```
v, f = igl.read_triangle_mesh("data/bunny.obj")
n = igl.per_face_normals(v, f, np.array([0,0,0]))
```
produces the error `ValueError: Invalid type (long, Col Major) for argument 'z'. Expected it to match argument 'v' which is of type (double, Row Major).` Can we convert int arrays and remove/fix the misleading error message about the col major (in this case the array is col and row major).

**Comment by fwilliams** [comment]
1D arrays are both column and row major and so the logic which generates the error message just picks column major. In that case, I'll print an error message where the 1D array major matches.  

auto-conversion is not supported in numpyeigen for 3 reasons:
1. It would introduce a copy
2. In some cases autoconversion is not well defined (see example below). 
3. What does it mean to pass in doubles as an index array? This could lead to weird behavior.

In the case of this issue, `z` is of type double and `f` is declared to be of types `int`, `long` or `longlong` (I assume). In this case, we could detect that `z` has a wrong type and automatically cast, however this could lead to weird behavior: What does it mean to pass in an array of doubles for indexing? In this particular case it's well defined since it's zeros, but what if you passed in `v` by mistake? This could lead to a crash.

Here's a case where autoconversion would not work at all: If you have 2 parameters `a` and `b` which are declared with `npe_matches` and can take on types `dense_double` and `dense_float`. Then the user passes in `a` as a float array and `b` as a double array. Which type do you pick?

**Comment by fwilliams** [comment]
In conclusion, I'll fix the error message so it doesn't have the column major problem, but I think this error actually makes sense semantically.
